package AIWeb::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'AIWeb::Schema',
    
    
);

=head1 NAME

AIWeb::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<AIWeb>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<AIWeb::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Gordon Marler

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
